"""initial

Revision ID: 6e80bb32c941
Revises: fc65ea3c86fd
Create Date: 2025-08-23 20:06:46.872803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e80bb32c941'
down_revision: Union[str, Sequence[str], None] = 'fc65ea3c86fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=False),
    sa.Column('address_number', sa.String(length=255), nullable=False),
    sa.Column('address_neighborhood', sa.String(length=255), nullable=False),
    sa.Column('address_city', sa.String(length=255), nullable=False),
    sa.Column('address_state', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('guest_quantity', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('properties')
    # ### end Alembic commands ###
