"""fix guests

Revision ID: 99fc782d7e21
Revises: 6e80bb32c941
Create Date: 2025-08-24 17:46:22.374135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fc782d7e21'
down_revision: Union[str, Sequence[str], None] = '6e80bb32c941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Passo 1: Adicionar a nova coluna permitindo valores nulos temporariamente
    op.add_column('reservations', sa.Column('guests_quantity', sa.Integer(), nullable=True))

    # Passo 2: Copiar os dados da coluna antiga para a nova
    op.execute("UPDATE reservations SET guests_quantity = guest_quantity")

    # Passo 3: Alterar a nova coluna para não permitir mais valores nulos
    op.alter_column('reservations', 'guests_quantity', nullable=False)
    
    # Passo 4: Remover a coluna antiga
    op.drop_column('reservations', 'guest_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('guest_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'guests_quantity')
    # ### end Alembic commands ###
